[package]
name = "chip8"
version = "0.1.0"
authors = ["Gian Lorenzo Meocci <glmeocci@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.34"
rand = "0.8.3"
